title: <p align="center"> Snehal Jadhav</p>
logo: /assets/img/Machine_Learning.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/snehal-jadhav-75944b8/">LinkedIn</a> |
  <a href="https://github.com/snehaljadhav2283">GitHub</a>
  
  <br>   
  Persuing Data Science and Machine Learning and Artificial Intelligence.
  Working in Risk Management division of Nomura from Last 10 Years.
  
  <br>
  </p>



theme: jekyll-theme-minimal
